# Generated by Django 4.0.6 on 2022-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('tel_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('registration_date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
        ),
    ]
